CREATE TABLE TB_NOTAS_SAIDA_XML (
	SAIDA_ID UNIQUEIDENTIFIER PRIMARY KEY,
	XML_CONTEUDO VARCHAR(MAX)
);

ALTER TABLE TB_NOTAS_SAIDA_XML
 ADD CONSTRAINT FK_NOTAS_SAIDA_XML_SAIDA
 FOREIGN KEY (SAIDA_ID) REFERENCES TB_NOTAS_SAIDA (ID);
