CREATE TABLE TB_NOTAS_SAIDA (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    BUSINESS_ID UNIQUEIDENTIFIER NOT NULL,
    CLIENTE_ID VARCHAR(50) NOT NULL,
    CPF_CNPJ_CLI VARCHAR(14) NOT NULL,
    NUMERO INT NOT NULL,
    SERIE INT NOT NULL,
    CHAVE_ACESSO VARCHAR(46) NOT NULL,
    PROTOCOLO VARCHAR(55),
    CFOP VARCHAR(4),
    DATA_EMISSAO DATETIME NOT NULL,
    VALOR_TOTAL DECIMAL(18,2) DEFAULT 0,
    BASE_ICMS DECIMAL(18,2) DEFAULT 0,
    VALOR_ICMS DECIMAL(18,2) DEFAULT 0,
    ALIQ_ICMS DECIMAL(18,2) DEFAULT 0,
    BASE_ST DECIMAL(18,2) DEFAULT 0,
    VALOR_ST DECIMAL(18,2) DEFAULT 0,
    OBS_NF VARCHAR(MAX),
);

ALTER TABLE TB_NOTAS_SAIDA 
   ADD CLIENTE_ID VARCHAR(50) NOT NULL,
   CPF_CNPJ_CLI VARCHAR(14) NOT NULL;

CREATE INDEX IDX_NOTAS_SAIDA_DOCUMENTO ON TB_NOTAS_SAIDA (CPF_CNPJ_CLI);

ALTER TABLE TB_NOTAS_SAIDA 
 ADD CONSTRAINT FK_NOTAS_SAIDA_CLIENTE 
 FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTES (ID);

 ALTER TABLE TB_NOTAS_SAIDA
    ADD MODELO INT NOT NULL;