IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_USERS')
CREATE TABLE TB_USERS (
	USERID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NAME NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(255) NOT NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME DEFAULT GETDATE()
);