IF OBJECT_ID('dbo.TB_BUSINESS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_BUSINESS (
        BUSINESS_ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT (NEWID()),
        CORPORATE_NAME NVARCHAR(200) NOT NULL,
        FANTASY_NAME NVARCHAR(200),
        CNPJ VARCHAR(14) NOT NULL UNIQUE,
        IE VARCHAR(20),
        UF CHAR(2) NOT NULL,
        ENVIRONMENT INT DEFAULT 1,
        LAST_NSU VARCHAR(20) DEFAULT ('0'),
        CERT_BASE64 VARCHAR(MAX),
        CERT_PASSWORD VARCHAR(100), 
        CERT_EXPIRATION DATETIME,
        CREATED_AT DATETIME DEFAULT (GETDATE()),
        UPDATED_AT DATETIME
    );
END;

SELECT * FROM dbo.TB_BUSINESS;
